export const CarListsData = [
  {
    id: 1,
    name: "Uber X",
    seat: "4",
    desc: "Affordable ,Everyday rides",
    amount: 1.1,
    Image: "/UberX_v1.png",
  },
  {
    id: 2,
    name: "Comfortable",
    seat: "4",
    desc: "Newer cars with extra legroom",
    amount: 1.6,
    Image: "/UberComfort.png",
  },
  {
    id: 3,
    name: "Uber XL",
    seat: "4",
    desc: "Affordable rides for the groups upto 6",
    amount: 1.8,
    Image: "/UberXL_New.png",
  },
  {
    id: 4,
    name: "Uber Pet",
    seat: "4",
    desc: "Affordable rides for you and your pet",
    amount: 2.0,
    Image: "/UberX_Pet.png",
  },
  {
    id: 5,
    name: "Black",
    seat: "4",
    desc: "Affordable ,Everyday rides",
    amount: 1.2,
    Image: "/Black_v1.png",
  },
];